title: esp32-smart-home
description: Public ESP32 smart home project with separate custom firmware and ESPHome tracks.
lang: en
baseurl: "/smarthome-technikerprojekt"
url: "https://devopsofchaos.github.io"
theme: minima
markdown: kramdown
