[platformio]
default_envs = master

[env]
platform = espressif32
framework = arduino
monitor_speed = 115200
lib_ldf_mode = deep+
build_flags =
    -D SH_PLATFORMIO=1

[env:master]
board = esp32-c3-devkitm-1
build_src_filter = +<master/> -<*>

[env:net_erl]
board = esp32-c3-devkitm-1
build_src_filter = +<net_erl/> -<*>

[env:net_zrl]
board = esp32-c3-devkitm-1
build_src_filter = +<net_zrl/> -<*>

[env:net_sen]
board = esp32-c3-devkitm-1
build_src_filter = +<net_sen/> -<*>

[env:bat_sen]
board = esp32-c3-devkitm-1
build_src_filter = +<bat_sen/> -<*>
