[platformio]
default_envs = master

[env]
platform = espressif32
framework = arduino
monitor_speed = 115200
lib_ldf_mode = deep+
build_flags =
    -D SH_PLATFORMIO=1

[env:master]
board = esp32-c3-devkitm-1
build_src_filter = -<*> +<master/>
build_flags =
    ${env.build_flags}
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
lib_deps =
    knolleary/PubSubClient @ ^2.8

[env:master_secondary]
board = esp32-c3-devkitm-1
build_src_filter = -<*> +<master/>
build_flags =
    ${env.build_flags}
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D MASTER_PROFILE=SH_MASTER_PROFILE_SECONDARY
lib_deps =
    knolleary/PubSubClient @ ^2.8

[env:net_erl]
board = esp32-c3-devkitm-1
build_src_filter = -<*> +<net_erl/>
build_flags =
    ${env.build_flags}
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1

[env:net_erl_hall_light]
board = esp32-c3-devkitm-1
build_src_filter = -<*> +<net_erl/>
build_flags =
    ${env.build_flags}
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D NET_ERL_PROFILE=SH_NET_ERL_PROFILE_HALL_LIGHT

[env:net_erl_kitchen_light]
board = esp32-c3-devkitm-1
build_src_filter = -<*> +<net_erl/>
build_flags =
    ${env.build_flags}
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D NET_ERL_PROFILE=SH_NET_ERL_PROFILE_KITCHEN_LIGHT

[env:net_zrl]
board = esp32-c3-devkitm-1
build_src_filter = -<*> +<net_zrl/>
build_flags =
    ${env.build_flags}
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1

[env:net_zrl_roller_shutter]
board = esp32-c3-devkitm-1
build_src_filter = -<*> +<net_zrl/>
build_flags =
    ${env.build_flags}
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D NET_ZRL_PROFILE=SH_NET_ZRL_PROFILE_ROLLER_SHUTTER

[env:net_sen]
board = esp32-c3-devkitm-1
build_src_filter = -<*> +<net_sen/>
build_flags =
    ${env.build_flags}
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
lib_deps =
    adafruit/DHT sensor library @ ^1.4.6

[env:net_sen_environment_stub]
board = esp32-c3-devkitm-1
build_src_filter = -<*> +<net_sen/>
build_flags =
    ${env.build_flags}
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D NET_SEN_PROFILE=SH_NET_SEN_PROFILE_ENVIRONMENT
lib_deps =
    adafruit/DHT sensor library @ ^1.4.6

[env:net_sen_bmp280_stub]
board = esp32-c3-devkitm-1
build_src_filter = -<*> +<net_sen/>
build_flags =
    ${env.build_flags}
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D NET_SEN_ENV_PROVIDER=SH_NET_SEN_ENV_PROVIDER_BMP280_STUB
lib_deps =
    adafruit/DHT sensor library @ ^1.4.6

[env:net_sen_bme280_ens160_stub]
board = esp32-c3-devkitm-1
build_src_filter = -<*> +<net_sen/>
build_flags =
    ${env.build_flags}
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D NET_SEN_ENV_PROVIDER=SH_NET_SEN_ENV_PROVIDER_BME280_STUB
    -D NET_SEN_AIR_PROVIDER=SH_NET_SEN_AIR_PROVIDER_ENS160_STUB
    -D NET_SEN_MOTION_PROVIDER=SH_NET_SEN_MOTION_PROVIDER_PIR_STUB
lib_deps =
    adafruit/DHT sensor library @ ^1.4.6

[env:net_sen_bmp280_veml_stub]
board = esp32-c3-devkitm-1
build_src_filter = -<*> +<net_sen/>
build_flags =
    ${env.build_flags}
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D NET_SEN_ENV_PROVIDER=SH_NET_SEN_ENV_PROVIDER_BMP280_STUB
    -D NET_SEN_LIGHT_PROVIDER=SH_NET_SEN_LIGHT_PROVIDER_VEML7700_STUB
lib_deps =
    adafruit/DHT sensor library @ ^1.4.6

[env:net_sen_bme280_ens160_veml_stub]
board = esp32-c3-devkitm-1
build_src_filter = -<*> +<net_sen/>
build_flags =
    ${env.build_flags}
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D NET_SEN_ENV_PROVIDER=SH_NET_SEN_ENV_PROVIDER_BME280_STUB
    -D NET_SEN_AIR_PROVIDER=SH_NET_SEN_AIR_PROVIDER_ENS160_STUB
    -D NET_SEN_LIGHT_PROVIDER=SH_NET_SEN_LIGHT_PROVIDER_VEML7700_STUB
    -D NET_SEN_MOTION_PROVIDER=SH_NET_SEN_MOTION_PROVIDER_PIR_STUB
lib_deps =
    adafruit/DHT sensor library @ ^1.4.6

[env:net_sen_sht41_veml_stub]
board = esp32-c3-devkitm-1
build_src_filter = -<*> +<net_sen/>
build_flags =
    ${env.build_flags}
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D NET_SEN_ENV_PROVIDER=SH_NET_SEN_ENV_PROVIDER_SHT41_STUB
    -D NET_SEN_LIGHT_PROVIDER=SH_NET_SEN_LIGHT_PROVIDER_VEML7700_STUB
lib_deps =
    adafruit/DHT sensor library @ ^1.4.6

[env:net_sen_ld2410c]
board = esp32-c3-devkitm-1
build_src_filter = -<*> +<net_sen/>
build_flags =
    ${env.build_flags}
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D NET_SEN_MOTION_PROVIDER=SH_NET_SEN_MOTION_PROVIDER_LD2410C
lib_deps =
    adafruit/DHT sensor library @ ^1.4.6

[env:net_sen_ld2410b]
board = esp32-c3-devkitm-1
build_src_filter = -<*> +<net_sen/>
build_flags =
    ${env.build_flags}
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D NET_SEN_MOTION_PROVIDER=SH_NET_SEN_MOTION_PROVIDER_LD2410B
lib_deps =
    adafruit/DHT sensor library @ ^1.4.6

[env:bat_sen]
board = esp32-c3-devkitm-1
build_src_filter = -<*> +<bat_sen/>
build_flags =
    ${env.build_flags}
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1

[env:bat_sen_window_contact]
board = esp32-c3-devkitm-1
build_src_filter = -<*> +<bat_sen/>
build_flags =
    ${env.build_flags}
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D BAT_SEN_PROFILE=SH_BAT_SEN_PROFILE_WINDOW_CONTACT

[env:bat_sen_door_contact]
board = esp32-c3-devkitm-1
build_src_filter = -<*> +<bat_sen/>
build_flags =
    ${env.build_flags}
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D BAT_SEN_PROFILE=SH_BAT_SEN_PROFILE_DOOR_CONTACT

[env:bat_sen_rain_node]
board = esp32-c3-devkitm-1
build_src_filter = -<*> +<bat_sen/>
build_flags =
    ${env.build_flags}
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D BAT_SEN_PROFILE=SH_BAT_SEN_PROFILE_RAIN_NODE

[env:bat_sen_wall_switch]
board = esp32-c3-devkitm-1
build_src_filter = -<*> +<bat_sen/>
build_flags =
    ${env.build_flags}
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D BAT_SEN_PROFILE=SH_BAT_SEN_PROFILE_WALL_SWITCH

[env:bat_sen_input_stub]
board = esp32-c3-devkitm-1
build_src_filter = -<*> +<bat_sen/>
build_flags =
    ${env.build_flags}
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D BAT_SEN_REED_PROVIDER=SH_BAT_SEN_REED_PROVIDER_STUB
    -D BAT_SEN_BUTTON_PROVIDER=SH_BAT_SEN_BUTTON_PROVIDER_STUB
    -D BAT_SEN_BUTTON_CHANNELS=2
    -D BAT_SEN_RAIN_PROVIDER=SH_BAT_SEN_RAIN_PROVIDER_STUB
