[platformio]
default_envs = master

[env]
platform = espressif32
framework = arduino
monitor_speed = 115200
lib_ldf_mode = deep+
build_flags =
    -D SH_PLATFORMIO=1

[env:master]
board = esp32-c3-devkitm-1
build_src_filter = -<*> +<master/>
build_flags =
    ${env.build_flags}
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
lib_deps =
    knolleary/PubSubClient @ ^2.8

[env:net_erl]
board = esp32-c3-devkitm-1
build_src_filter = -<*> +<net_erl/>
build_flags =
    ${env.build_flags}
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1

[env:net_zrl]
board = esp32-c3-devkitm-1
build_src_filter = -<*> +<net_zrl/>
build_flags =
    ${env.build_flags}
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1

[env:net_sen]
board = esp32-c3-devkitm-1
build_src_filter = -<*> +<net_sen/>
build_flags =
    ${env.build_flags}
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1

[env:bat_sen]
board = esp32-c3-devkitm-1
build_src_filter = -<*> +<bat_sen/>
build_flags =
    ${env.build_flags}
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
